[package]
name = "gdrust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
libc = "0.2.147"
wasm-bindgen = "0.2.87"

[build-dependencies]
bindgen = "0.66.1"

